##########################
#
#	Build UNIX send and respond executables
#

CC = gcc
CFLAGS = -Wall 

all :	unixrespond unixsend

clean :
	rm -f *.o unixrespond unixsend *~ core*

# -----------------------------------------------

unixrespond :	unixrespond.c

unixsend :	unixsend.c


