/*** BeginHeader  ********************************************/
#ifndef __LIMITS_H
#define __LIMITS_H
/*** EndHeader ***********************************************/

/* START LIBRARY DESCRIPTION *********************************************
LIMITS.H
	Copyright (c) 2000, Z-World.

DESCRIPTION:
	Numerical limits for C variable types.

SUPPORT LIB'S:
END DESCRIPTION **********************************************************/

/*** BeginHeader */
#define CHAR_BIT             8
#define UCHAR_MAX          255
#define CHAR_MIN             0
#define CHAR_MAX           255
#define MB_LEN_MAX           1
#define SHRT_MIN        -32767
#define SHRT_MAX         32767
#define USHRT_MAX        65535u
#define INT_MIN         -32767
#define INT_MAX          32767
#define UINT_MAX         65535u
#define LONG_MIN   -2147483647
#define LONG_MAX    2147483647
#define ULONG_MAX   4294967295u
/*** EndHeader */

/*** BeginHeader  ********************************************/
#endif
/*** EndHeader ***********************************************/
